channels:
  - litex-hub
  - conda-forge
  - bioconda
dependencies:
  - open_pdks.sky130a=1.0.290
  - magic
  - openroad
  - netgen
  - yosys
  - gdstk
  - cairosvg
  - svgutils
  - iverilog
  - pyyaml
  - click
  - pandas
  - tcllib
  - snakemake
  - python
  - pip
  - pip:
      - kubernetes
